
language: python
python:
  - "3.5"

# command to install dependencies
install:
  - pip install tqdm
  - pip install numpy
  - pip install cython
  - python setup.py build_ext --inplace

# command to run tests
script:
  - nosetests experiments/test-guthrie-model.py
